const {JSDOM,VirtualConsole}=require(process.env.FORM_JSDOM||'jsdom');
const fs=require('node:fs');const assert=require('node:assert/strict');
const publicRoot=fs.existsSync('dist/index.html')?'dist':'.';const html=fs.readFileSync(publicRoot+'/index.html','utf8');const script=fs.readFileSync(publicRoot+'/app.js','utf8');let passed=0;
function app(hash=''){
 const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(html,{url:'http://localhost/'+hash,runScripts:'outside-only',virtualConsole:vc});const w=dom.window;
 w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});
 w.document.startViewTransition=()=>{throw Error('Navigation must not depend on view transitions')};
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
 w.HTMLDialogElement.prototype.close=function(){if(!this.open)return;this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};
 w.eval(script);const d=w.document;
 return {w,d,errors,click:s=>{const el=d.querySelector(s);assert.ok(el,s);el.click();return el},fill:(s,value)=>{d.querySelector(s).value=value;d.querySelector(s).dispatchEvent(new w.Event('input',{bubbles:true}))},submit:s=>d.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),text:()=>d.body.textContent,close:()=>dom.window.close()};
}
function test(name,fn){const a=app();try{fn(a);assert.deepEqual(a.errors,[]);console.log('PASS '+name);passed++}finally{a.close()}}
const modalOpen=a=>assert.ok(a.d.querySelector('#modal').open);
function publish(a,title='Audit project'){a.click('[data-publish]');a.fill('#title',title);a.fill('#description','An original creative project with a thoughtful story.');a.fill('#tools','Photography and Figma');a.submit('#publish-form')}
test('All top-level routes and four artist profiles',a=>{for(const route of ['discover','collaborate','circle','support','profile','features','artist:maya','artist:arjun','artist:leila','artist:nia']){a.w.eval(`navigate('${route}')`);assert.ok(a.d.querySelector('#app h1'));assert.equal(a.d.body.dataset.view,route)}});
test('Malformed and unknown routes recover',a=>{for(const route of ['%E0%A4%A','badroute']){a.w.history.replaceState(null,'','#'+route);a.w.eval('loadView()');assert.equal(a.d.body.dataset.view,'discover')}});
test('Support and circle tabs have restorable routes',a=>{a.click('[data-view="support"]');for(const tab of ['wallet','market','projects']){a.click(`[data-support-tab="${tab}"]`);assert.equal(a.w.location.hash,'#support/'+tab);a.w.eval('loadView()');assert.equal(a.d.querySelector('.tab.active').dataset.supportTab,tab)}a.click('[data-view="circle"]');for(const tab of ['saved','people','feed']){a.click(`[data-circle-tab="${tab}"]`);assert.equal(a.w.location.hash,'#circle/'+tab)}});
test('Every publish form field, label and blank area remains interactive',a=>{a.click('[data-publish]');for(const selector of ['#title','label[for="title"]','#discipline','#description','#tools','#modal-content','.tiny-note']){a.click(selector);modalOpen(a)}a.fill('#title','Test');assert.equal(a.d.querySelector('#title').value,'Test')});
test('Publish validation and successful project/creator navigation',a=>{a.click('[data-publish]');a.fill('#title','   ');a.submit('#publish-form');modalOpen(a);assert.match(a.text(),/excluding extra spaces/);a.fill('#title','<img src=x onerror=alert(1)>');a.fill('#description','A sufficiently detailed and original creative project.');a.fill('#tools','Figma');a.submit('#publish-form');assert.equal(a.d.body.dataset.view,'profile');assert.equal(a.d.querySelector('#app img'),null);assert.match(a.d.querySelector('#app').textContent,/<img src=x/);a.click('[data-project]');modalOpen(a);a.click('[data-person="you"]');assert.equal(a.d.body.dataset.view,'profile');assert.equal(a.d.querySelector('#modal').open,false)});
test('Category filters, live search and empty reset',a=>{for(const category of ['Music','Film','Design','Photography','Art']){a.click(`[data-category="${category}"]`);assert.equal(a.d.querySelectorAll('.work-card').length,1)}a.fill('#search','zzzz');assert.equal(a.d.querySelectorAll('.work-card').length,0);a.click('[data-reset-search]');assert.match(a.text(),/Good work/);a.fill('#search','Maya');assert.equal(a.d.querySelectorAll('.work-card').length,1)});
test('Save/unsave, following/unfollow and feed consistency',a=>{a.click('[data-save="softer"]');a.click('[data-view="circle"]');a.click('[data-circle-tab="saved"]');assert.equal(a.d.querySelectorAll('.work-card').length,1);a.click('[data-save="softer"]');assert.equal(a.d.querySelectorAll('.work-card').length,0);a.click('[data-circle-tab="people"]');a.click('[data-follow="maya"]');assert.match(a.text(),/Find your people/);a.click('[data-circle-tab="feed"]');assert.match(a.text(),/No studio notes yet/)});
test('Project modal typing, likes update cards, rewards only once',a=>{a.click('[data-project="concrete"]');a.click('#comment');modalOpen(a);a.click('[data-like="concrete"]');assert.match(a.d.querySelector('#app').textContent,/187/);a.fill('#comment','      ');a.submit('#comment-form');assert.match(a.text(),/excluding extra spaces/);for(let i=0;i<2;i++){a.fill('#comment','Thoughtful original comment for this photo project.');a.submit('#comment-form')}assert.equal(a.d.querySelectorAll('.comment').length,2);a.click('.close');a.click('[data-view="support"]');a.click('[data-support-tab="wallet"]');assert.match(a.text(),/260/)});
test('Early picks enforce limit and show visible feedback inside dialog',a=>{for(const id of ['softer','concrete','train','bloom']){a.w.eval(`projectModal('${id}')`);a.click(`[data-pick="${id}"]`)}assert.match(a.d.querySelector('#dialog-toast').textContent,/all three/);modalOpen(a)});
test('Introductions validate URLs and can be reviewed',a=>{a.w.eval("navigate('artist:maya')");a.click('[data-intro="maya"]');a.click('#intro');modalOpen(a);a.fill('#intro','I would love to collaborate on your independent project.');a.fill('#portfolio','javascript:alert(1)');a.submit('#intro-form');modalOpen(a);assert.match(a.text(),/https/);a.fill('#portfolio','https://example.com/portfolio');a.submit('#intro-form');a.click('[data-intro="maya"]');assert.match(a.d.querySelector('#modal-content').textContent,/I would love/);assert.equal(a.d.querySelector('#modal-content a').href,'https://example.com/portfolio')});
test('Collaboration filters and submitted request review',a=>{a.click('[data-view="collaborate"]');a.click('[data-collab-filter="Paid"]');assert.equal(a.d.querySelectorAll('.brief').length,2);a.click('[data-collab-filter="Collaboration"]');assert.equal(a.d.querySelectorAll('.brief').length,1);a.click('[data-apply="zine"]');a.fill('#intro','I can illustrate original stories for your zine project.');a.submit('#intro-form');assert.match(a.text(),/View request/);a.click('[data-apply="zine"]');assert.match(a.d.querySelector('#modal-content').textContent,/illustrate original/)});
test('Perk redemption, repeat protection and insufficient-points explanation',a=>{a.w.eval("navigate('support')");a.click('[data-support-tab="wallet"]');a.click('[data-redeem="notes"]');assert.match(a.text(),/140/);a.click('[data-redeem="notes"]');modalOpen(a);assert.match(a.text(),/YOU’RE ON THE LIST/);a.click('.close');a.click('[data-redeem="studio"]');modalOpen(a);assert.match(a.d.querySelector('#modal-content').textContent,/need 360 more/)});
test('Buy/sell update balances; invalid and excessive orders rejected',a=>{a.w.eval("navigate('support')");a.click('[data-support-tab="market"]');a.click('[data-trade="maya"][data-side="buy"]');a.click('#quantity');modalOpen(a);for(const value of ['0','-1','1.5','99999']){a.fill('#quantity',value);a.submit('#trade-form');modalOpen(a)}a.fill('#quantity','4');a.submit('#trade-form');assert.match(a.text(),/₹9,900/);assert.match(a.text(),/124 coins/);a.click('[data-trade="maya"][data-side="sell"]');a.fill('#quantity','124');a.submit('#trade-form');assert.match(a.text(),/₹13,000/);a.click('[data-trade="maya"][data-side="sell"]');assert.match(a.text(),/No coins to sell yet/)});
test('Backing updates shared balance and rejects invalid/insufficient amounts',a=>{a.w.eval("navigate('support')");a.click('[data-back="softer"]');a.click('#back-kind');modalOpen(a);a.fill('#back-amount','5000');a.submit('#back-form');a.click('[data-back="softer"]');a.fill('#back-amount','5000');a.submit('#back-form');a.click('[data-back="softer"]');a.fill('#back-amount','500');a.submit('#back-form');modalOpen(a);assert.match(a.text(),/Not enough demo cash/);a.click('.close');a.click('[data-support-tab="market"]');assert.match(a.text(),/₹0/);a.click('[data-trade="maya"][data-side="buy"]');assert.match(a.text(),/Not enough demo cash/)});
test('Ordinary content clicks never trigger navigation or discard modal',a=>{a.w.eval("navigate('support')");a.click('[data-support-tab="wallet"]');a.click('.points-card');assert.equal(a.w.location.hash,'#support/wallet');a.click('[data-redeem="studio"]');a.click('.modal-title');modalOpen(a)});
console.log(`\n${passed} audit suites passed.`);
